numero_couleur = {
    0: "vert",
    1: "rouge",
    2: "noir",
    3: "rouge",
    4: "noir",
    5: "rouge",
    6: "noir",
    7: "rouge",
    8: "noir",
    9: "rouge",
    10: "noir",
    11: "noir",
    12: "rouge",
    13: "noir",
    14: "rouge",
    15: "noir",
    16: "rouge",
    17: "noir",
    18: "rouge",
    19: "rouge",
    20: "noir",
    21: "rouge",
    22: "noir",
    23: "rouge",
    24: "noir",
    25: "rouge",
    26: "noir",
    27: "rouge",
    28: "noir",
    29: "noir",
    30: "rouge",
    31: "noir",
    32: "rouge",
    33: "noir",
    34: "rouge",
    35: "noir",
    36: "rouge",
}

def getCouleur(numero):
    return numero_couleur[numero]


